### ISSUE TITLE
Html report - too big table

### ISSUE THREAD

**Issue by Alexey-T** [kvichans/cuda_options_editor#65]
Таблица в 2 раза шире чем экран. на скрине видно изза какой опции.
![long-tabl](https://user-images.githubusercontent.com/4154978/28514969-98b1030e-7064-11e7-83a1-0749014f2534.png)

**Comment by kvichans** [comment]
Подумаю над этим.
Можете предложить решение?

**Comment by Alexey-T** [comment]
wrap-ить строку в этой опции.

**Comment by kvichans** [comment]
Научите, как это выразить на HTML

**Comment by Alexey-T** [comment]
https://stackoverflow.com/questions/11250501/wrap-long-html-tables-to-next-line

**Comment by kvichans** [comment]
Не понял, что предлагают на СОФ.
Можете выдать отчет, скопировать файл, в копии сделать нужные изменения и передать мне оба файла?

**Comment by Alexey-T** [comment]
предлагают сделать стиль в CSS и заюзать его в HTML для  table. не могу

**Comment by kvichans** [comment]
В отчете уже применяется CSS
```css
    <style type="text/css">
td, th, body {
    color:          #000;
    font-family:    Verdana, Arial, Helvetica, sans-serif;
    font-size:      12px;
}
table {
    border-width:   1px;
    border-spacing: 2px;
    border-color:   gray;
    border-collapse:collapse;
}
table td, table th{
    border-width:   1px;
    padding:        1px;
    border-style:   solid;
    border-color:   gray;
}
pre {
    margin:         0;
    padding:        0;
}
td.nxt {
    color:          grey;
}
td.win {
    font-weight:    bold;
}
    </style>
```
Что изменить/добавить?
